name: MagicMirror
version: '0.1'
main: org.papermc.magicMirror.MagicMirror
api-version: '1.21'
load: STARTUP
commands:
  sethome:
    description: "Sets the location your Magic Mirror teleports"
    usage: /sethome
