name: MagicMirror
version: '1.0'
main: org.papermc.magicMirror.MagicMirror
api-version: '1.21'
load: STARTUP
commands:
  sethome:
    description: "Sets the location your Magic Mirror teleports"
    usage: /sethome
  reloadmagicmirror:
    description:  "Reload the config for magic mirror"
    usage: /reloadmagicmirror
    permission: magicmirror.reload
permissions:
  magicmirror.reload:
    description: "Allows reloading the MagicMirror configuration"
    default: op